Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        role:
            type: integer
            nullable: false
            unsigned: false
        name:
            type: string
            nullable: true
            length: 200
            fixed: false
        surname:
            type: string
            nullable: true
            length: 200
            fixed: false
        email:
            type: string
            nullable: true
            length: 255
            fixed: false
        password:
            type: string
            nullable: true
            length: 255
            fixed: false
        image:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
