BlogBundle\Entity\Category:
    type: entity
    repositoryClass: BlogBundle\Repositories\CategoryRepository
    table: categories
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 200
            fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            fixed: false
    oneToMany:
        entry:
            targetEntity: Entry
            cascade: ["persist"]
            mappedBy: category
    lifecycleCallbacks: {  }
