BlogBundle\Entity\EntryTag:
    type: entity
    table: entry_tag
    indexes:
        entry_id:
            columns:
                - entry_id
        tag_id:
            columns:
                - tag_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        entry:
            targetEntity: Entry
            cascade: {  }
            mappedBy: null
            inversedBy: entryTag
            joinColumns:
                entry_id:
                    referencedColumnName: id
            orphanRemoval: false
        tag:
            targetEntity: Tag
            cascade: {  }
            mappedBy: null
            inversedBy: entryTag
            joinColumns:
                tag_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
